//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiksRadarDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijava
    {
        public int Id { get; set; }
        public Nullable<int> Kor_Id { get; set; }
        public System.DateTime Vrijeme { get; set; }
        public string RFID { get; set; }
        public bool Pristup { get; set; }
        public string Ime { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
